#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."
ynh_setup_source --dest_dir="$install_dir"

chown -R "$app:www-data" "$install_dir"

#=================================================
# NODE JS INSTALLATION
#=================================================
ynh_script_progression "Installing pnpm..."
corepack enable pnpm
corepack use pnpm@9.15.5

#=================================================
# INSTALLING DEPENDENCIES
#=================================================
ynh_script_progression "Installing dependencies..."
pushd "$install_dir"
    ynh_exec_as_app pnpm install --frozen-lockfile
    ynh_exec_as_app pnpm build
popd

#=================================================
# INITIALIZE AND STORE SETTINGS
#=================================================
ynh_script_progression "Generating .env file..."

app_secret=$(ynh_string_random --length=32)
ynh_app_setting_set --key=key --value=$key

redis_db=$(ynh_redis_get_free_db)
ynh_app_setting_set --key=redis_db --value=$redis_db

# TODO: based on the storage strategy, we need to create the .env file differently
# if [ "$storage_strategy" == "local" ]; then
#     ynh_config_add --template=".env.local" --destination="$install_dir/.env"
# else
#     ynh_config_add --template=".env.s3" --destination="$install_dir/.env"
# fi

#=================================================
# APP CONFIG FILES
#=================================================
ynh_script_progression "Adding $app's configuration files..."

ynh_config_add --template=".env" --destination="$install_dir/.env"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

# Create a dedicated NGINX config
ynh_config_add_nginx

# Create a dedicated systemd config
ynh_config_add_systemd

# Use logrotate to manage application logfile(s)
ynh_config_add_logrotate
touch /var/log/$app/$app.log
chown -R $app:$app /var/log/$app/

yunohost service add $app --description="Docmost" --log="/var/log/$app/$app.log"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

# Start a systemd service
ynh_systemctl --service="$app" --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
